export type WorkItem = {
	id: string;
	title: string;
	description: string;
	tags: string[];
	icon?: 'link' | 'github';
	link?: string;
};

export default [
	{
		id: '1',
		title: 'Servicecam',
		description:
			"Servicecam enables car mechanics & dealerships to visually document errors and create offers for their customers. It's used by more than 20.000 delerships.",
		tags: ['React', 'AWS', 'Java', 'Kotlin', 'MySql', 'Node.js', 'React-Native'],
		icon: 'link',
		link: 'https://www.volkswagen.ch/de/dienstleistungen/fahrzeug-reparatur/service-cam.html'
	},
	{
		id: '2',
		title: 'TimeTracker',
		description:
			'Mobile App that assists the user by conveniently tracking their working hours and calculating the billable project time for their customers.',
		tags: ['React-Native', 'Typescript', 'SqLite']
	},
	{
		id: '3',
		title: 'Serverless Twitter Bot',
		description:
			"Small app that posts tweets, generated by OpenAI's ChatGPT4. Running on AWS Lambda, based on a cron based event bridge schedule.",
		tags: ['AWS-Lambda', 'Twitter-API', 'OpenAi-API', 'Typescript', 'AWS'],
		icon: 'github',
		link: 'https://github.com/timges/serverless-twitter-bot'
	},
	{
		id: '4',
		title: 'Beverage Payment',
		description:
			'Mobile App to organize beverages for your office. Allows you to purchase & offer drinks for/from your colleagues',
		tags: ['Typescript', 'React-Native', 'deno', 'MongoDB']
	},
	{
		id: '5',
		title: 'Volkswagen GroupUI',
		description:
			'Design system and component library of the Volkswagen Group. It is the standard for all internal Volkswagen applications. Winner of the RedDot Design award in 2019',
		tags: ['Typescript', 'Stencil.js', 'Figma', 'GitHub-Actions', 'AWS', 'Svelte'],
		icon: 'link',
		link: 'https://www.red-dot.org/de/project/groupui-41315'
	},
	{
		id: '6',
		title: 'Personal Website',
		description:
			'This is the website you are currently visiting. Built with SvelteKit, Typescript & SCSS. Hosted on Vercel.',
		tags: ['Typescript', 'SvelteKit', 'SCSS', 'GitHub-Actions', 'Vercel'],
		icon: 'github',
		link: 'https://github.com/timges'
	}
] as WorkItem[];
