<script lang="ts">
	import Flyout from './flyout.svelte';
	import WorkItem from './work-item.svelte';
	import items from './items';

	let showFlyout: boolean = true;
	let activeItemId: string = '0';
	$: activeItem = items?.find((item) => item.id === activeItemId);

	function closeFlyout() {
		showFlyout = false;
	}
	function openFlyout(itemId: string) {
		activeItemId = itemId;
		if (showFlyout) {
			showFlyout = false;
		}
		setTimeout(() => {
			showFlyout = true;
		}, 200);
	}
</script>

<section id="work">
	<h2>THINGS, I BUILT</h2>
	{#each items as item (item.id)}
		<div class="work-item">
			<WorkItem
				id={item.id}
				title={item.title}
				description={item.description}
				tags={item.tags}
				on:container-click={() => openFlyout(item.id)}
				icon={item.icon}
				link={item.link}
			/>
		</div>
	{/each}
	<!-- <WorkItem
			id="1"
			title="Servicecam"
			description="Application trying to enable car mechanics & dealerships to visually document errors and create offer for their customers with more than 10.000 users"
			tags={['React.js', 'AWS', 'Java', 'Kotlin', 'MySql', 'Node', 'React-Native']}
			icon="link"
			link="https://www.volkswagen.ch/de/dienstleistungen/fahrzeug-reparatur/service-cam.html"
			on:container-click={openFlyout}
		/>
	</div>
	<div class="work-item">
		<WorkItem
			id="2"
			title="TimeTracker"
			description="Mobile Application that allows users to conveniently track their working ours and calculate a billable amount"
			tags={['React-Native', 'Typescript', 'Node.js']}
			on:container-click={openFlyout}
		/>
	</div>
	<div class="work-item">
		<WorkItem
			id="3"
			title="Auto-Tweeter"
			description="Small app which posts tweets, generated by OpenAI's ChatGPT2. Hosted containerized @ my home on a raspberry pi"
			tags={['Node', 'Docker', 'Twitter Api', 'OpenAi', 'Typescript']}
			on:container-click={openFlyout}
			icon="github"
			link="https://github.com/timges/auto-tweet"
		/>
	</div>
	<div class="work-item">
		<WorkItem
			id="4"
			title="Office Beverage Payment"
			description="Mobile App to organize beverages for your office. Allows you to purchase & offer drinks for/from your colleagues"
			tags={['Typescript', 'React-Native', 'deno', 'MongoDB']}
			on:container-click={openFlyout}
		/>
	</div>
	<div class="work-item">
		<WorkItem
			id="5"
			title="Volkswagen GroupUI"
			description="Design System of the Volkswagen Group. It won the RedDot Design award of 2019"
			tags={['Typescript', 'Stencil.js', 'Figma', 'Style Dictionary', 'Github Actions']}
			on:container-click={openFlyout}
			icon="link"
			link="https://www.red-dot.org/de/project/groupui-41315"
		/>
	</div>
	<div class="work-item">
		<WorkItem
			id="6"
			title="Servicecam"
			description="Application trying to enable car mechanics & dealerships to visually document errors and create offer for their customers with more than 10.000 users"
			tags={['React.js', 'AWS', 'Java', 'Kotlin', 'MySql', 'Node', 'React-Native']}
			on:container-click={openFlyout}
			icon="link"
		/> -->
</section>
<Flyout
	show={showFlyout}
	imgs={activeItem?.flyout.imgs ?? []}
	content={activeItem?.flyout.content ?? ''}
	title={activeItem?.title ?? ''}
	on:close={closeFlyout}
/>

<style lang="scss">
	@import '../../../../../sass/main.scss';

	section {
		max-width: 100%;
		background-color: $color-bg-light;
		display: grid;
		grid-template-columns: repeat(8, 1fr);
		gap: $spacing-l;
		padding: $spacing-xxl 0;
	}

	h2 {
		grid-column: 2 / span all;
		white-space: nowrap;
		color: $color-text-on-bg-light;
		line-height: $line-height-large;
	}

	@for $i from 1 through 3 {
		.work-item:nth-of-type(#{$i}) {
			grid-column: ($i * 2) / span 2;
			grid-row: 2;
		}

		.work-item:nth-last-of-type(#{$i}) {
			grid-column: ($i * 2) / span 2;
			grid-row: 3;
		}
	}

	@media screen and (max-width: 1100px) {
		.work-item:nth-of-type(even) {
			grid-column: 5 / span 3;
		}
		.work-item:nth-of-type(odd) {
			grid-column: 2 / span 3;
		}
		.work-item:nth-of-type(n + 3) {
			grid-row: 3;
		}
		.work-item:nth-of-type(n + 5) {
			grid-row: 4;
		}
	}

	@media screen and (max-width: 768px) {
		section {
			display: flex;
			flex-direction: column;
			gap: $spacing-l;
			padding: $spacing-xxl $spacing-l;
		}

		h2 {
			align-self: flex-start;
		}
	}
</style>
