<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 clouds.glb --transform --types
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Events, type Slots } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { tweened } from 'svelte/motion';
	import { sineInOut } from 'svelte/easing';

	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group>;

	const offsetAnimation = tweened(-1, {
		duration: 10000,
		easing: sineInOut,
	});

	$: if ($offsetAnimation === -1) {
		offsetAnimation.set(1);
	}
	$: if ($offsetAnimation === 1) {
		offsetAnimation.set(-1);
	}
	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Cloud_1: THREE.Mesh;
			Cloud_1001: THREE.Mesh;
			Cloud_2: THREE.Mesh;
			Cloud_3: THREE.Mesh;
			Cloud_4: THREE.Mesh;
		};
		materials: {
			Cloud_Mat: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/3d-models/clouds-transformed.glb', { useDraco: true });
</script>

{#if $gltf}
	<T is={ref} {...$$restProps}>
		<T.Group name="Scene" position={[0,0,0]}>
			<T.Mesh
				name="Cloud_1"
				geometry={$gltf.nodes.Cloud_1.geometry}
				material={$gltf.materials.Cloud_Mat}
				position={[3.96 + $offsetAnimation, 6.17 + $offsetAnimation * 0.5, -22.42]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[0.84, 0.84, 0.93]}
			/>
			<T.Mesh
				name="Cloud_1001"
				geometry={$gltf.nodes.Cloud_1001.geometry}
				material={$gltf.materials.Cloud_Mat}
				position={[-35.07 + $offsetAnimation * 0.8, -5 + $offsetAnimation * 1.5, -35.7]}
				rotation={[-Math.PI, 0.77, -Math.PI]}
				scale={[0.84, 0.84, 0.93]}
			/>
			<T.Mesh
				name="Cloud_2"
				geometry={$gltf.nodes.Cloud_2.geometry}
				material={$gltf.materials.Cloud_Mat}
				position={[0.07 - $offsetAnimation * 1.2, 10.2, -17.97]}
				rotation={[0, Math.PI / 2, 0]}
				scale={[3.01, 3.01, 3.24]}
			/>
			<T.Mesh
				name="Cloud_3"
				geometry={$gltf.nodes.Cloud_3.geometry}
				material={$gltf.materials.Cloud_Mat}
				position={[-9.32, 12.95 - $offsetAnimation, -40.11]}
				rotation={[-Math.PI, 0.94, -Math.PI]}
				scale={[1.85, 1.65, 1.88]}
			/>
			<T.Mesh
				name="Cloud_4"
				geometry={$gltf.nodes.Cloud_4.geometry}
				material={$gltf.materials.Cloud_Mat}
				position={[-11.71, 5.76, -20.49 + $offsetAnimation * 1.5]}
				rotation={[0, Math.PI / 2, 0]}
				scale={1.19}
			/>
		</T.Group>

		<slot {ref} />
	</T>
{/if}
