<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 tim-3d.glb --transform --types
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group, Material, Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from 'three';
	import { T, type Events, type Slots } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import { createEventDispatcher } from 'svelte';

	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group>;

	const ref = new Group();
	const gltf = useGltf('/3d-models/tim-3d-transformed.glb', { useDraco: true });
	const dispatch = createEventDispatcher();
	const { actions, mixer } = useGltfAnimations(gltf, ref);

	$: $gltf && $actions && mixer ? onLoad() : null;

	let glassMaterial: THREE.MeshStandardMaterial | undefined;

	function setupCharacter() {
		glassMaterial = new MeshPhysicalMaterial({
			...$gltf!.materials.glass,
			opacity: 0.5,
			transparent: true,
			thickness: 0.5
		});

    $gltf?.scene.traverse((child) => {
      if(child.name === "glasses" ) {
        console.log(child);
        (child.children[1] as Mesh).material = glassMaterial as Material;
      }
    })
	}

	function onLoad() {
		setupCharacter();
    console.log($gltf);
    
		dispatch('loaded', { actions: $actions, mixer: mixer });
	}
</script>

{#if $gltf}
	<T is={ref} {...$$restProps} position={[0, 0, 0]}>
		<T.Group name="Scene">
			<T.Group name="Armature" position={[-0.02, 1.22, 0]}>
				<T is={$gltf.nodes.root} />
				<T is={$gltf.nodes.IKLegPolel} />
				<T is={$gltf.nodes.IKTargetl} />
				<T is={$gltf.nodes.IKLegPoler} />
				<T is={$gltf.nodes.IKTargetr} />
				<T.Group name="character">
					<T.SkinnedMesh
						name="Cube002"
						geometry={$gltf.nodes.Cube002.geometry}
						material={$gltf.materials.skin}
						skeleton={$gltf.nodes.Cube002.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_1"
						geometry={$gltf.nodes.Cube002_1.geometry}
						material={$gltf.materials.black}
						skeleton={$gltf.nodes.Cube002_1.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_2"
						geometry={$gltf.nodes.Cube002_2.geometry}
						material={$gltf.materials.jeans}
						skeleton={$gltf.nodes.Cube002_2.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_3"
						geometry={$gltf.nodes.Cube002_3.geometry}
						material={$gltf.materials['t-shirt']}
						skeleton={$gltf.nodes.Cube002_3.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_4"
						geometry={$gltf.nodes.Cube002_4.geometry}
						material={$gltf.materials.hair}
						skeleton={$gltf.nodes.Cube002_4.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_5"
						geometry={$gltf.nodes.Cube002_5.geometry}
						material={$gltf.materials.earring}
						skeleton={$gltf.nodes.Cube002_5.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_6"
						geometry={$gltf.nodes.Cube002_6.geometry}
						material={$gltf.materials['Material.006']}
						skeleton={$gltf.nodes.Cube002_6.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_7"
						geometry={$gltf.nodes.Cube002_7.geometry}
						material={$gltf.materials['Material.007']}
						skeleton={$gltf.nodes.Cube002_7.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_8"
						geometry={$gltf.nodes.Cube002_8.geometry}
						material={$gltf.materials['Material.011']}
						skeleton={$gltf.nodes.Cube002_8.skeleton}
						castShadow
					/>
					<T.SkinnedMesh
						name="Cube002_9"
						geometry={$gltf.nodes.Cube002_9.geometry}
						material={$gltf.materials['Material.012']}
						skeleton={$gltf.nodes.Cube002_9.skeleton}
						castShadow
					/>
				</T.Group>
				<!-- <T.Group
          name="glasses"
          scale={[1.14, 1.12, 0.99]}
        >
          <T.Mesh
            name="Cube005"
            geometry={$gltf.nodes.Cube005.geometry}
            material={$gltf.materials['glasses-frame']}
          />
          <T.Mesh
            name="Cube005_1"
            geometry={$gltf.nodes.Cube005_1.geometry}
            material={glassMaterial}
          />
        </T.Group> -->
			</T.Group>
		</T.Group>

		<slot {ref} />
	</T>
{/if}
