<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 terrain.glb --transform --types
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Events, type Slots } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group>;

	export const ref = new Group();
	export let terrainRotation = { x: 0, y: 0, z: 0 };

	const gltf = useGltf<any>('/3d-models/terrain_small-transformed.glb', { useDraco: true });
</script>

{#if $gltf}
	<T is={ref} {...$$restProps}>
		<T.Group name="Scene">
			<T.Group name="Icosphere" position={[0, -20.24, 0]} scale={20.11} rotation={[terrainRotation.x, terrainRotation.y, terrainRotation.z]}>
				<T.Mesh
					name="Icosphere003"
					geometry={$gltf.nodes.Icosphere003.geometry}
					material={$gltf.materials['planet-grass']}
				/>
				<T.Mesh
					name="Icosphere003_1"
					geometry={$gltf.nodes.Icosphere003_1.geometry}
					material={$gltf.materials['planet-ocean']}
				/>
				<T.Mesh
					name="Icosphere003_2"
					geometry={$gltf.nodes.Icosphere003_2.geometry}
					material={$gltf.materials['Material.003']}
				/>
				<T.Group
					name="forest-house"
					position={[0.64, 0.73, 0.48]}
					rotation={[0.75, 0.23, -0.67]}
					scale={0.05}
				>
					<T.Mesh
						name="Cube"
						geometry={$gltf.nodes.Cube.geometry}
						material={$gltf.materials.house}
					/>
					<T.Mesh
						name="Cube_1"
						geometry={$gltf.nodes.Cube_1.geometry}
						material={$gltf.materials.roof}
					/>
					<T.Mesh
						name="Cube_2"
						geometry={$gltf.nodes.Cube_2.geometry}
						material={$gltf.materials.schornstein}
					/>
					<T.Mesh
						name="Cube_3"
						geometry={$gltf.nodes.Cube_3.geometry}
						material={$gltf.materials.door}
					/>
					<T.Mesh
						name="Cube_4"
						geometry={$gltf.nodes.Cube_4.geometry}
						material={$gltf.materials.darker}
					/>
				</T.Group>
				<T.Group
					name="mountain-poly"
					position={[-0.31, 0.69, 0.05]}
					rotation={[0.22, -0.2, 0.3]}
					scale={0.008}
				>
					<T.Mesh
						name="mesh_Group51674_12268Mountain3001"
						geometry={$gltf.nodes.mesh_Group51674_12268Mountain3001.geometry}
						material={$gltf.materials['mountain-rock.001']}
					/>
					<T.Mesh
						name="mesh_Group51674_12268Mountain3001_1"
						geometry={$gltf.nodes.mesh_Group51674_12268Mountain3001_1.geometry}
						material={$gltf.materials.door}
					/>
				</T.Group>
				<T.Group
					name="road-poly"
					rotation={[Math.PI / 2, 0, -Math.PI / 2]}
					scale={[1.01, 0.09, 1.01]}
				>
					<T.Mesh
						name="Cylinder001"
						geometry={$gltf.nodes.Cylinder001.geometry}
						material={$gltf.materials['Material.005']}
					/>
					<T.Mesh
						name="Cylinder001_1"
						geometry={$gltf.nodes.Cylinder001_1.geometry}
						material={$gltf.materials.door}
					/>
				</T.Group>
				<T.Group
					name="tree-big005"
					position={[0.33, 0.84, 0.39]}
					rotation={[0.52, 0.1, -0.34]}
					scale={0.02}
				>
					<T.Mesh
						name="Circle005_Material014_0007"
						geometry={$gltf.nodes.Circle005_Material014_0007.geometry}
						material={$gltf.materials['Material.042']}
					/>
					<T.Mesh
						name="Circle005_Material014_0007_1"
						geometry={$gltf.nodes.Circle005_Material014_0007_1.geometry}
						material={$gltf.materials['Material.041']}
					/>
				</T.Group>
				<T.Group
					name="tree-big006"
					position={[0.41, 0.79, 0.42]}
					rotation={[0.49, 0.11, -0.52]}
					scale={0.02}
				>
					<T.Mesh
						name="Circle005_Material014_0007"
						geometry={$gltf.nodes.Circle005_Material014_0007.geometry}
						material={$gltf.materials['Material.042']}
					/>
					<T.Mesh
						name="Circle005_Material014_0007_1"
						geometry={$gltf.nodes.Circle005_Material014_0007_1.geometry}
						material={$gltf.materials['Material.041']}
					/>
				</T.Group>
				<T.Group
					name="tree-big007"
					position={[0.36, 0.78, 0.48]}
					rotation={[0.52, 0.1, -0.34]}
					scale={0.02}
				>
					<T.Mesh
						name="Circle005_Material014_0007"
						geometry={$gltf.nodes.Circle005_Material014_0007.geometry}
						material={$gltf.materials['Material.042']}
					/>
					<T.Mesh
						name="Circle005_Material014_0007_1"
						geometry={$gltf.nodes.Circle005_Material014_0007_1.geometry}
						material={$gltf.materials['Material.041']}
					/>
				</T.Group>
				<T.Group
					name="tree-big008"
					position={[0.26, 0.83, 0.46]}
					rotation={[0.52, 0.1, -0.34]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle005_Material014_0007"
						geometry={$gltf.nodes.Circle005_Material014_0007.geometry}
						material={$gltf.materials['Material.042']}
					/>
					<T.Mesh
						name="Circle005_Material014_0007_1"
						geometry={$gltf.nodes.Circle005_Material014_0007_1.geometry}
						material={$gltf.materials['Material.041']}
					/>
				</T.Group>
				<T.Group
					name="tree-big009"
					position={[0.34, 0.59, 0.72]}
					rotation={[0.8, -0.01, -0.4]}
					scale={0.02}
				>
					<T.Mesh
						name="Circle005_Material014_0007"
						geometry={$gltf.nodes.Circle005_Material014_0007.geometry}
						material={$gltf.materials['Material.042']}
					/>
					<T.Mesh
						name="Circle005_Material014_0007_1"
						geometry={$gltf.nodes.Circle005_Material014_0007_1.geometry}
						material={$gltf.materials['Material.041']}
					/>
				</T.Group>
				<T.Group
					name="tree-bushy001"
					position={[0.41, 0.66, 0.61]}
					rotation={[0.77, -0.07, -0.41]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle_Material002_0002"
						geometry={$gltf.nodes.Circle_Material002_0002.geometry}
						material={$gltf.materials['Material.033']}
					/>
					<T.Mesh
						name="Circle_Material002_0002_1"
						geometry={$gltf.nodes.Circle_Material002_0002_1.geometry}
						material={$gltf.materials['Material.031']}
					/>
					<T.Mesh
						name="Circle_Material002_0002_2"
						geometry={$gltf.nodes.Circle_Material002_0002_2.geometry}
						material={$gltf.materials['Material.032']}
					/>
				</T.Group>
				<T.Group
					name="tree-bushy002"
					position={[0.32, 0.71, 0.61]}
					rotation={[0.65, -0.03, -0.29]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle_Material002_0002"
						geometry={$gltf.nodes.Circle_Material002_0002.geometry}
						material={$gltf.materials['Material.033']}
					/>
					<T.Mesh
						name="Circle_Material002_0002_1"
						geometry={$gltf.nodes.Circle_Material002_0002_1.geometry}
						material={$gltf.materials['Material.031']}
					/>
					<T.Mesh
						name="Circle_Material002_0002_2"
						geometry={$gltf.nodes.Circle_Material002_0002_2.geometry}
						material={$gltf.materials['Material.032']}
					/>
				</T.Group>
				<T.Mesh
					name="tree-dead"
					geometry={$gltf.nodes['tree-dead'].geometry}
					material={$gltf.materials['Material.043']}
					position={[-0.49, 0.78, 0.36]}
					rotation={[0.76, -0.4, 0.53]}
					scale={0.01}
				/>
				<T.Mesh
					name="tree-dead001"
					geometry={$gltf.nodes['tree-dead001'].geometry}
					material={$gltf.materials['Material.043']}
					position={[-0.33, 0.8, 0.47]}
					rotation={[0.25, 0.65, 0.4]}
					scale={0.01}
				/>
				<T.Mesh
					name="tree-dead002"
					geometry={$gltf.nodes['tree-dead002'].geometry}
					material={$gltf.materials['Material.043']}
					position={[-0.2, 0.87, 0.42]}
					rotation={[0.39, 0.3, 0.33]}
					scale={0.01}
				/>
				<T.Group
					name="tree-fir001"
					position={[0.4, 0.72, 0.56]}
					rotation={[0.61, -0.15, -0.29]}
					scale={0.05}
				>
					<T.Mesh
						name="Circle001_Material005_0004"
						geometry={$gltf.nodes.Circle001_Material005_0004.geometry}
						material={$gltf.materials['Material.035']}
					/>
					<T.Mesh
						name="Circle001_Material005_0004_1"
						geometry={$gltf.nodes.Circle001_Material005_0004_1.geometry}
						material={$gltf.materials['Material.034']}
					/>
				</T.Group>
				<T.Group
					name="tree-idk004"
					position={[0.43, 0.6, 0.66]}
					rotation={[0.85, 0.11, -0.41]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle003_Material011_0006"
						geometry={$gltf.nodes.Circle003_Material011_0006.geometry}
						material={$gltf.materials['Material.039']}
					/>
					<T.Mesh
						name="Circle003_Material011_0006_1"
						geometry={$gltf.nodes.Circle003_Material011_0006_1.geometry}
						material={$gltf.materials['Material.040']}
					/>
				</T.Group>
				<T.Group
					name="tree-idk005"
					position={[0.43, 0.75, 0.49]}
					rotation={[0.56, 0.22, -0.35]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle003_Material011_0006"
						geometry={$gltf.nodes.Circle003_Material011_0006.geometry}
						material={$gltf.materials['Material.039']}
					/>
					<T.Mesh
						name="Circle003_Material011_0006_1"
						geometry={$gltf.nodes.Circle003_Material011_0006_1.geometry}
						material={$gltf.materials['Material.040']}
					/>
				</T.Group>
				<T.Group
					name="tree-idk006"
					position={[0.3, 0.77, 0.54]}
					rotation={[0.71, 0.17, -0.29]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle003_Material011_0006"
						geometry={$gltf.nodes.Circle003_Material011_0006.geometry}
						material={$gltf.materials['Material.039']}
					/>
					<T.Mesh
						name="Circle003_Material011_0006_1"
						geometry={$gltf.nodes.Circle003_Material011_0006_1.geometry}
						material={$gltf.materials['Material.040']}
					/>
				</T.Group>
				<T.Group
					name="tree-idk007"
					position={[0.36, 0.68, 0.62]}
					rotation={[0.85, 0.1, -0.41]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle003_Material011_0006"
						geometry={$gltf.nodes.Circle003_Material011_0006.geometry}
						material={$gltf.materials['Material.039']}
					/>
					<T.Mesh
						name="Circle003_Material011_0006_1"
						geometry={$gltf.nodes.Circle003_Material011_0006_1.geometry}
						material={$gltf.materials['Material.040']}
					/>
				</T.Group>
				<T.Group
					name="tree-palm001"
					position={[-0.78, 0.31, 0.52]}
					rotation={[-0.61, 0.69, 1.64]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle002_Material008_0002"
						geometry={$gltf.nodes.Circle002_Material008_0002.geometry}
						material={$gltf.materials['Material.036']}
					/>
					<T.Mesh
						name="Circle002_Material008_0002_1"
						geometry={$gltf.nodes.Circle002_Material008_0002_1.geometry}
						material={$gltf.materials['Material.037']}
					/>
					<T.Mesh
						name="Circle002_Material008_0002_2"
						geometry={$gltf.nodes.Circle002_Material008_0002_2.geometry}
						material={$gltf.materials['Material.038']}
					/>
				</T.Group>
				<T.Group
					name="tree-palm002"
					position={[-0.75, 0.34, 0.54]}
					rotation={[0.7, 0.3, 0.94]}
					scale={0.02}
				>
					<T.Mesh
						name="Circle002_Material008_0002"
						geometry={$gltf.nodes.Circle002_Material008_0002.geometry}
						material={$gltf.materials['Material.036']}
					/>
					<T.Mesh
						name="Circle002_Material008_0002_1"
						geometry={$gltf.nodes.Circle002_Material008_0002_1.geometry}
						material={$gltf.materials['Material.037']}
					/>
					<T.Mesh
						name="Circle002_Material008_0002_2"
						geometry={$gltf.nodes.Circle002_Material008_0002_2.geometry}
						material={$gltf.materials['Material.038']}
					/>
				</T.Group>
				<T.Group
					name="tree-tornado001"
					position={[0.5, 0.69, 0.58]}
					rotation={[0.4, -0.51, -0.68]}
					scale={0.01}
				>
					<T.Mesh
						name="Circle007_Material018_0002"
						geometry={$gltf.nodes.Circle007_Material018_0002.geometry}
						material={$gltf.materials['Material.044']}
					/>
					<T.Mesh
						name="Circle007_Material018_0002_1"
						geometry={$gltf.nodes.Circle007_Material018_0002_1.geometry}
						material={$gltf.materials['Material.045']}
					/>
				</T.Group>
				<T.Group
					name="tree-tornado002"
					position={[0.5, 0.57, 0.69]}
					rotation={[0.4, -0.51, -0.68]}
					scale={0.02}
				>
					<T.Mesh
						name="Circle007_Material018_0002"
						geometry={$gltf.nodes.Circle007_Material018_0002.geometry}
						material={$gltf.materials['Material.044']}
					/>
					<T.Mesh
						name="Circle007_Material018_0002_1"
						geometry={$gltf.nodes.Circle007_Material018_0002_1.geometry}
						material={$gltf.materials['Material.045']}
					/>
				</T.Group>
			</T.Group>
		</T.Group>

		<slot {ref} />
	</T>
{/if}
