<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 clouds.glb --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type ActionName = 'Cloud_1Action' | 'Cloud_1Action.001' | 'Cloud_2Action' | 'Cloud_3Action' | 'Cloud_4Action'
  type GLTFResult = {
    nodes: {
      Cloud_1: THREE.Mesh
      Cloud_1001: THREE.Mesh
      Cloud_2: THREE.Mesh
      Cloud_3: THREE.Mesh
      Cloud_4: THREE.Mesh
    }
    materials: {
      Cloud_Mat: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('/clouds-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Group name="Scene">
      <T.Mesh
        name="Cloud_1"
        geometry={$gltf.nodes.Cloud_1.geometry}
        material={$gltf.materials.Cloud_Mat}
        position={[1.96, 6.17, -22.42]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.84, 0.84, 0.93]}
      />
      <T.Mesh
        name="Cloud_1001"
        geometry={$gltf.nodes.Cloud_1001.geometry}
        material={$gltf.materials.Cloud_Mat}
        position={[-17.07, 7.27, -9.7]}
        rotation={[-Math.PI, 0.77, -Math.PI]}
        scale={[0.84, 0.84, 0.93]}
      />
      <T.Mesh
        name="Cloud_2"
        geometry={$gltf.nodes.Cloud_2.geometry}
        material={$gltf.materials.Cloud_Mat}
        position={[0.07, 10.2, -17.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.01, 3.01, 3.24]}
      />
      <T.Mesh
        name="Cloud_3"
        geometry={$gltf.nodes.Cloud_3.geometry}
        material={$gltf.materials.Cloud_Mat}
        position={[-29.32, 12.95, -40.11]}
        rotation={[-Math.PI, 0.94, -Math.PI]}
        scale={[1.85, 1.65, 1.88]}
      />
      <T.Mesh
        name="Cloud_4"
        geometry={$gltf.nodes.Cloud_4.geometry}
        material={$gltf.materials.Cloud_Mat}
        position={[-9.71, 5.76, -20.49]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.19}
      />
    </T.Group>

    <slot {ref} />
  </Three>
{/if}
