<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 terrain.glb --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type ActionName = 'SphereAction' | 'UnityGlTF_rootAction' | 'node_Mountain3_-1129440Action' | 'CylinderAction'
  type GLTFResult = {
    nodes: {
      planet: THREE.Mesh
      mesh_Group51674_12268Mountain3: THREE.Mesh
      mesh_Group51674_12268Mountain3_1: THREE.Mesh
      Cylinder: THREE.Mesh
      Cylinder_1: THREE.Mesh
    }
    materials: {
      ['Material.003']: THREE.MeshStandardMaterial
      ['mountain-rock']: THREE.MeshStandardMaterial
      ['mountain-ice']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('/terrain-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Group name="Scene">
      <T.Mesh
        name="planet"
        geometry={$gltf.nodes.planet.geometry}
        material={$gltf.materials['Material.003']}
        position={[0, -54.22, 0]}
        scale={54.17}
      >
        <T.Group name="mountain" position={[-0.05, 0.89, 0.06]} scale={0.02}>
          <T.Group name="mountin-node-mesh" position={[-21.15, -15.73, -7.01]} rotation={[0, 0, 0.6]} scale={0.52}>
            <T.Mesh
              name="mesh_Group51674_12268Mountain3"
              geometry={$gltf.nodes.mesh_Group51674_12268Mountain3.geometry}
              material={$gltf.materials['mountain-rock']}
            />
            <T.Mesh
              name="mesh_Group51674_12268Mountain3_1"
              geometry={$gltf.nodes.mesh_Group51674_12268Mountain3_1.geometry}
              material={$gltf.materials['mountain-ice']}
            />
          </T.Group>
        </T.Group>
      </T.Mesh>
      <T.Group
        name="road"
        position={[0, -54.26, 0.07]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[54.3, 2.82, 54.3]}
      >
        <T.Mesh name="Cylinder" geometry={$gltf.nodes.Cylinder.geometry} material={$gltf.materials['Material.005']} />
        <T.Mesh
          name="Cylinder_1"
          geometry={$gltf.nodes.Cylinder_1.geometry}
          material={$gltf.materials['mountain-ice']}
        />
      </T.Group>
    </T.Group>

    <slot {ref} />
  </Three>
{/if}
