<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 tim-3d.glb --transform --types
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type ActionName = 'idle' | 'walk-cycle' | 'waving' | 'glasses'
  type GLTFResult = {
    nodes: {
      Cube005: THREE.Mesh
      Cube005_1: THREE.Mesh
      Cube002: THREE.SkinnedMesh
      Cube002_1: THREE.SkinnedMesh
      Cube002_2: THREE.SkinnedMesh
      Cube002_3: THREE.SkinnedMesh
      Cube002_4: THREE.SkinnedMesh
      Cube002_5: THREE.SkinnedMesh
      Cube002_6: THREE.SkinnedMesh
      Cube002_7: THREE.SkinnedMesh
      Cube002_8: THREE.SkinnedMesh
      Cube002_9: THREE.SkinnedMesh
      root: THREE.Bone
      IKLegPolel: THREE.Bone
      IKTargetl: THREE.Bone
      IKLegPoler: THREE.Bone
      IKTargetr: THREE.Bone
    }
    materials: {
      ['glasses-frame']: THREE.MeshStandardMaterial
      glass: THREE.MeshStandardMaterial
      skin: THREE.MeshStandardMaterial
      black: THREE.MeshStandardMaterial
      jeans: THREE.MeshStandardMaterial
      ['t-shirt']: THREE.MeshStandardMaterial
      hair: THREE.MeshStandardMaterial
      earring: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
      ['Material.011']: THREE.MeshStandardMaterial
      ['Material.012']: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('/tim-3d-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Group name="Scene">
      <T.Group name="Armature" position={[-0.02, 1.22, 0]}>
        <Three type={$gltf.nodes.root} />
        <Three type={$gltf.nodes.IKLegPolel} />
        <Three type={$gltf.nodes.IKTargetl} />
        <Three type={$gltf.nodes.IKLegPoler} />
        <Three type={$gltf.nodes.IKTargetr} />
        <T.Group name="character">
          <T.SkinnedMesh
            name="Cube002"
            geometry={$gltf.nodes.Cube002.geometry}
            material={$gltf.materials.skin}
            skeleton={$gltf.nodes.Cube002.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_1"
            geometry={$gltf.nodes.Cube002_1.geometry}
            material={$gltf.materials.black}
            skeleton={$gltf.nodes.Cube002_1.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_2"
            geometry={$gltf.nodes.Cube002_2.geometry}
            material={$gltf.materials.jeans}
            skeleton={$gltf.nodes.Cube002_2.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_3"
            geometry={$gltf.nodes.Cube002_3.geometry}
            material={$gltf.materials['t-shirt']}
            skeleton={$gltf.nodes.Cube002_3.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_4"
            geometry={$gltf.nodes.Cube002_4.geometry}
            material={$gltf.materials.hair}
            skeleton={$gltf.nodes.Cube002_4.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_5"
            geometry={$gltf.nodes.Cube002_5.geometry}
            material={$gltf.materials.earring}
            skeleton={$gltf.nodes.Cube002_5.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_6"
            geometry={$gltf.nodes.Cube002_6.geometry}
            material={$gltf.materials['Material.006']}
            skeleton={$gltf.nodes.Cube002_6.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_7"
            geometry={$gltf.nodes.Cube002_7.geometry}
            material={$gltf.materials['Material.007']}
            skeleton={$gltf.nodes.Cube002_7.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_8"
            geometry={$gltf.nodes.Cube002_8.geometry}
            material={$gltf.materials['Material.011']}
            skeleton={$gltf.nodes.Cube002_8.skeleton}
          />
          <T.SkinnedMesh
            name="Cube002_9"
            geometry={$gltf.nodes.Cube002_9.geometry}
            material={$gltf.materials['Material.012']}
            skeleton={$gltf.nodes.Cube002_9.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>

    <slot {ref} />
  </Three>
{/if}
